name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          a="chore(deps): test comment"
          b=6
          if [[ $a == chore(deps)* ]]
          then
             echo "a is equal to b"
          else
             echo "a is not equal to b"
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."
